user:
  username: shd
  nickname: ""
site:
  title: shanghaiDAO
  subtitle: shanghaiDAO
  description: shanghaiDAO
  author: shanghaiDAO
  keywords:
    - shanghaiDAO
  favicon: https://storageapi.fleek.co/casimir-crystal-team-bucket/metanetwork/users/metaio-storage/favicon.ico
  avatar: https://storageapi.fleek.co/andoroyur-team-bucket/metanetwork/users/metaio-storage/fajtplryaie0upd8bzvwha2eah5o8hqxtjfzyt0r.jpeg
  configId: 150
  language: en
  timezone: Asia/Shanghai
  domain: shanghaidao.metaspaces.me
  metaSpacePrefix: shanghaidao
gateway:
  ipfs:
    baseUrl: https://ipfs.fleek.co/ipfs/
  dataViewer:
    baseUrl: https://meta-network-data-viewer.vercel.app/
